services:
  ingress:
    container_name: mwc_ingress
    restart: always
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    image: mwc-nginx:latest
    volumes:
      - ./conf/nginx-ingress/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx-ingress/conf.d:/etc/nginx/conf.d:ro
      - ./conf/nginx-ingress/snippets:/etc/nginx/snippets:ro
      - ./log/nginx:/var/log/nginx
      - ./conf/certs:/etc/certs:ro
      - ./static:/static:ro
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    depends_on:
      - accelerator
  accelerator:
    image: varnish:7.5.0
    container_name: mwc_accelerator
    restart: always
    volumes:
      - ./conf/varnish/default.vcl:/etc/varnish/default.vcl:ro
    tmpfs:
      - /tmp/varnish:exec
    environment:
      - VARNISH_SIZE=3G
    depends_on:
      - fastcgi
  fastcgi:
    container_name: mwc_fastcgi
    restart: always
    image: mwc-nginx:latest
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    volumes:
      - ./conf/nginx-fastcgi/nginx.conf:/etc/nginx/nginx.conf:ro
      - mediawiki-data:/var/www/html:ro
    depends_on:
      - app
    ports:
      - 8080:8080
  jobrunner:
    container_name: mwc_jobrunner
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    image: mwc-mediawiki:latest
    volumes:
      - mediawiki-data:/var/www/html:ro
      - ./conf/mediawiki/LocalSettings.php:/mw-mount/LocalSettings.php:ro 
      - ./log/jobrunner:/var/log/jobrunner
    restart: always
    command: ["/bin/sh", "-c", "/src/runner.sh >> /var/log/jobrunner/runJobs.log 2>&1"]
    depends_on:
      - app
  app:
    container_name: mwc_app
    build:
      context: .
      dockerfile: ./docker/app-Dockerfile
    image: mwc-mediawiki:latest
    volumes:
      - mediawiki-data:/var/www/html
      - ./conf/mediawiki/LocalSettings.php:/mw-mount/LocalSettings.php:ro
      - ./conf/php/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./log/php-fpm/fpm-php.www.log:/var/log/fpm-php.www.log:ro
      - /tmp/mediawiki-debug:/mediawiki-debug
    restart: always
    depends_on:
      - db
  db:
    image: mariadb:11
    container_name: mwc_database
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./data/mariadb:/var/lib/mysql
      - ./conf/mariadb:/etc/mysql/conf.d
    environment:
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_ROOT_PASSWORD: test
      MARIADB_AUTO_UPGRADE: true
  redis:
    image: redis:7.2.4-bookworm
    container_name: mwc_objcache
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
      - ./conf/redis:/usr/local/etc/redis:ro


volumes:
  mediawiki-data:
    name: mediawiki-data
  redis-data:
    name: redis-data
